### ISSUE TITLE
Override the php xdebug extension path for tests

### ISSUE THREAD

**Issue by aplysie** [itiqiti/dev-lib#2]
When defining custom php xdebug extension path, it is overrided by the default one.

**Comment by ohoareau** [comment]
Proposal: add a new location for xdebug.so :

    $expectedXDebugSoLocations = [
            '/usr/local/opt/php56-xdebug/xdebug.so',
            '/usr/local/opt/php70-xdebug/xdebug.so',
    ];

**Comment by aplysie** [comment]
I am using php70 with xdebug on MacOsX installed with brew.
I found a way to fix this in case of specific xdebug extension path:
I created a dev.json at the root path of the project and overrided the php_extra_phpunit_opts parameter:

{
    "config": {
        "php_extra_phpunit_opts": "-d zend_extension=/usr/local/opt/php70-xdebug/xdebug.so"
    }
}
