### ISSUE TITLE
StringServiceTest::testSlugify : Unit tests failed

### ISSUE THREAD

**Issue by michel-maier** [itiqiti/dev-lib#6]
There were 2 failures:

1) Tests\Itq\Common\Service\StringServiceTest::testSlugify with data set #2 ('Ab cé', 'abce')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'abce'
+'abc'

***/src/common-lib/tests/Service/StringServiceTest.php:67

2) Tests\Itq\Common\Service\StringServiceTest::testSlugify with data set #3 ('Âç-cÈ', 'acce')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'acce'
+'c'

***/src/common-lib/tests/Service/StringServiceTest.php:67

**Comment by ohoareau** [comment]
Can you dump the result of :

    php -m

**Comment by michel-maier** [comment]
[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
intl
json
libxml
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xdebug
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Xdebug
Zend OPcache

**Comment by michel-maier** [comment]
Moved to common-lib
